language: php

sudo: false

matrix:
    include:
        - php: 5.5
        - php: 5.6
    fast_finish: true

before_script:
  - echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ "$deps" == "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-source; fi

script: ./vendor/bin/phpunit